#build stage
FROM node:alpine3.22 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
#RUN npm install
RUN npm run build

##run stage
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
